
version: '2'

services:
  itest:
    build: .
    container_name: itest
    links:
      - kafka
      - zookeeper
    volumes:
      - .:/mount
    command: ./run_tests.sh
    environment:
      - KAFKA_VERSION=2.2.0

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
    logging:
      driver: none  # Hide output
    expose:
      - "9092"
    links:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    logging:
      driver: none  # Hide output
    expose:
      - "2181"
